[package]
name = "api_server"
version = "0.1.0"
edition = "2021"

[dependencies]
aead = "0.5.2"
base64 = "0.22.1"
chacha20poly1305 = "0.10.1"
mysql = "25.0.1"
rand = "0.8.5"
tokio = { version = "1.41.0", features = ["full"] }
warp = "0.3.7"
